### ISSUE TITLE
new tag cannot be added

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#20]
I created a new tag - "mocktail" - and I can't seem to add it to the drink "Steph's Request". I also don't know if the intention was that you could add tags right from the drink add/edit screen but that doesn't work.

**Comment by gthole** [comment]
Hmm.  I can't reproduce this bug.  I'm able to add `mocktail` to Steph's Request both in the Details view and in the Add/Edit screen.  I wonder if I should just remove the browser side caching, since it seems to be causing troubles.

**Comment by jelloeggy** [comment]
Try adding a new tag and adding it to a drink, does that work for you?

Is there anything else you'd like me to try before you rip it out?

**Comment by gthole** [comment]
I added `sour` and then added a Margarita recipe with the new tag and it worked fine for me.  (Really quite confused.)  You're reloading the browser after adding the tag and before returning to the UI, right?  I'm sorry it's been consistently been weird for you!

**Comment by jelloeggy** [comment]
I'm glad it's been weird for me, makes me feel useful.

I honestly don't know what changed or what I might have done in my browser
between trying out the functionality before and now. I will close out my
browser again and see but if it requires full cache clearing then yes, it
might be worth removing the browser cache.

**Comment by jelloeggy** [comment]
I closed my browser session and reopened.
- I tried to add mocktail to "Steph's Request" and it would not save:  I type "mocktail" into the "edit tags" space, click "Save" and the whole thing disappears.
- I went to "Margarita" (where I could see your tag) and tried to add the tag of "sweet". I click save and both your tag and mine disappear. When I click out of the recipe and back, "sour" returns, "sweet" is not there.

I cleared my browser cache.
- Tried adding mocktail and it worked as expected.
- I added a new tag via the admin panel, added it to a drink, and it worked fine.

I wonder if maybe there is something about using Chrome in a Chromebook environment - maybe it retains far more browser state than a normal OS? I just don't know what would have happened between when it worked fine and when it stopped working. Maybe another deployment in between?

My feeling is either we close the bug and I just make sure to always clear cached between deployments (which means we need a way for me to be notified of deployments), or you think about changing the browser caching (maybe make a trigger that forces explicit clearing post deployment, when a new version is noticed? that would be nice).

**Comment by gthole** [comment]
OK, clearly I need to be testing this thing in Chrome too instead of just Firefox.

> I wonder if maybe there is something about using Chrome in a Chromebook environment - maybe it retains far more browser state than a normal OS?

^ That sounds like a possible suspect.  I clearly can't depend on browser reloads to clear javascript app memory caching.

I've adjusted the tags caching approach so that the javascript app always goes back to the server to check to make sure if it still has the latest tags.  That should prevent the whole "please reload your browser every time you add a new tag" thing.

For what it's worth, there are a couple of different caching issues on interplay here.  One was that I had configured the server to say "any document you get from this server can cached forever", which is clearly wrong for JSON data.  The other was the javascript app caching strategy, which happens in the application memory, so reloading the page should have resolved that.

The first one should have been resolved yesterday when I removed that server configuration and you cleared your cache in Chrome settings.  The second one I just rolled out, so that should help.  My intuition is that deployments are a red herring on this issue.

(Also, I changed the color of the tags in the recipe list to be less prominent, since I was finding them pretty distracting.  Hope this works OK for you too.)

If you have some time, reload your page, (you'll know you have the new version if the tags in the recipe list are a new color), give it another try and let me know if it's any better?

Phew!  It's nice to have someone else looking at this and calling me out on my bugs.  Thanks, madam!

**Comment by jelloeggy** [comment]
The tag color didn't bug me but the change showed up without any crazy browser shenanigans and I can add tags to drinks without issue. Let's close this one and I'll open new if it happens again.

Also, if you want me to try other browsers in my general user/testing for new features let me know and I'll get Firefox.

**Comment by gthole** [comment]
I think just testing on Chrome and on your phone will be good for me.  Thanks!
