### ISSUE TITLE
Please add UOM administration

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#23]
It would be nice to be able to administer units of measures (i.e. add "rinse") in the admin console.

**Comment by gthole** [comment]
+1  It'll take a little work since they're currently hard-coded, but I've run into this a bunch too while doing data entry.

**Comment by gthole** [comment]
Done!  Want to check it & close this?

**Comment by gthole** [comment]
You'll have to reload your browser page for this one, by the way (no cache clearing required, though).  I changed the API contract, which I'll have to be a lot more careful about later if/when there are more users, but I figure that for now it's OK to make you refresh the page now and then.

**Comment by jelloeggy** [comment]
Yes, refreshing is no big deal, it was the cache clearing that seemed
problematic.

Unfortunately, this does not seem to be working! I can see the new section
but if I go to "Add unit of measure" there is no place to actually type the
new UOM. This happens on both Desktop and mobile.

**Comment by gthole** [comment]
This is what I get for coding right before bed last night.  I'd set the "name" parameter to be read-only since it's the primary key for that table, and it shouldn't be updated once it's set.  But that obviously broke the ability to create new UOMs, which was the whole point.

Fixed and deployed.  Thanks for the catch :)

**Comment by jelloeggy** [comment]
QA badge unlocked!
