### ISSUE TITLE
Show a sum of recipes returned after filter

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#30]
It would be really helpful to have a total at the top of the recipe filter that tells you how many recipes were returned after each filter (starting by showing the total recipes when you first land on the recipes page - also impressive!) Given how many recipes we have now it would be good to know how much more filtering you need to do to get to a usable list, and it's not immediately apparent after your initial search.

**Comment by gthole** [comment]
How's this?
<img width="520" alt="Screen Shot 2019-03-26 at 8 04 09 PM" src="https://user-images.githubusercontent.com/1581949/55041210-74213200-5002-11e9-9f8c-6325cc5c61e8.png">

(It makes me want to cache that first page of results so that the HTML can be drawn faster.  I'll open a separate issue for that.)

**Comment by jelloeggy** [comment]
The UI is fine - will the number change as you filter?

**Comment by gthole** [comment]
Yep!  It's deployed now, so give it a try.

**Comment by jelloeggy** [comment]
Ah, its awesome. Amazing the mental difference it makes in understanding what you're looking at. Huzzah!
