### ISSUE TITLE
Keep my position in the scroll view when i tap into a drink someone is trying and navigate back

### ISSUE THREAD

**Issue by kateswanson-toast** [gthole/drink-stash#57]
when you are scrolling through the feed of recent people who made what and you tap one then go back it scrolls you back to the top .. i use the feed a lot so it would be nice to not have to find my place again!

you guys rock by the way!!

**Comment by gthole** [comment]
Great suggestion. This will probably require some refactoring since we load resources from the API with each page view, so the previous scroll position is not available until after the state update following the data hook. I'll keep thinking about it and see what I can come up with.

**Comment by kateswanson-toast** [comment]
You rock!  Honestly the scroll thing would probably save me like 10 minutes a day.  This app is life-changing by the way - mad kudos. Eventually I'll be a better front end developer and try to help

**Comment by gthole** [comment]
Definitely working on this, and have some decent ideas, but nothing final yet.

Currently my best plan is to let the browser handle it with [history.scrollRestoration](https://developer.mozilla.org/en-US/docs/Web/API/History/scrollRestoration), but this will mean tracking the last `body` height of each path after render in the application context, with hooks for the view component to update the context after render. (That's not always easy, since sometimes the browser height is adjusted down in sub-components, like the activity list.)

So, I'll keep thinking about it. Definitely want to save you the 10 minutes a day (plus reduce frustration when making a drink. Nobody wants that.)

**Comment by gthole** [comment]
Deployed! [Here's the approach I used](https://github.com/gthole/drink-stash/blob/master/ui/src/components/ScrollMemory/index.js), which needs some adjustments made to it, but this works for now.

**Comment by kateswanson-toast** [comment]
You rock Greg!!

**Comment by gthole** [comment]
This has been re-reported.

**Comment by gthole** [comment]
Re-fixed. Still can't say I'm happy with the race condition on the render/page-height store. Leaving a note for myself on the technical details here.

Alternate approach: make a `useScrollMemory` hook that stores the page height to the cache based on a state dependency (e.g the `resp` for `RecipeList` component, and `activity` for the `ActivityDetails` component) and does not set the cache if the dependency is false-y. This makes the cache setting process properly a post-render hook and de-couples it from the `useAlertedEffect` service hook. But in the `RecipeDetails` view there are multiple such data loads and it doesn't seem to be restoring the correct page height.

The on-render `ScrollMemory` component also has some issues - probably need to switch to using a `useLayoutEffect` with no dependencies to register the `onpopstate` event handler.

If all else fails, there's always this [polyfill](https://github.com/janpaul123/delayed-scroll-restoration-polyfill) which would be less code to maintain. I can't say that I love it either, but I wouldn't have to think about it either. Just drop and go.
